### ISSUE TITLE
You can use Jefferson-Henrique/GetOldTweets-python

### ISSUE THREAD

**Issue by eleweek** [chrjguill/Twitter-scraper#1]
Hi, I've just stumbled upon your repo. I thought you may be interested to know that you can get a lot of old tweets using web scraper-like technique. 

This code works for me: https://github.com/Jefferson-Henrique/GetOldTweets-python

**Comment by chrjguill** [comment]
Thanks; I mostly just needed this for a research term project. I'll keep that in mind if I need that in the future!

**Comment by eleweek** [comment]
Ah, I suspected that my suggestion may be a bit too late, but figured it won't hurt to share the link.

**Comment by chrjguill** [comment]
I used [chrjguill/twitter-livescraper](https://GitHub.com/chrjguill/twitter-livescraper) for my stuff instead, since that's what I really needed in the end (and all the existing solutions kinda sucked).

Thanks you, though!
